_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
Model:
    value: |-
        DQN(
          (linear1): Linear(in_features=43, out_features=128, bias=True)
          (linear2): Linear(in_features=128, out_features=64, bias=True)
          (output): Linear(in_features=64, out_features=16, bias=True)
        )
Schedule:
    value: 'Counter({0: 1, 1000000: 1, 2000000: 1, 3000000: 1, 4000000: 1, 5000000: 1, 6000000: 1, 7000000: 1, 8000000: 1, 9000000: 1, 10000000: 1, 11000000: 1, 12000000: 1, 13000000: 1, 14000000: 1, 15000000: 1, 16000000: 1, 17000000: 1, 18000000: 1, 19000000: 1, 20000000: 1}) gamma=0.8'
batch_size:
    value: 128
checkpoint:
    value: Data/checkpoint14.pth
decay:
    value: 0
device:
    value: cpu
epochs:
    value: 20000
epochs per hat update:
    value: 3
gamma:
    value: 0.95
learning_rate:
    value: 0.0007
name:
    value: Herb_Keeper DDQN 14
start_epoch:
    value: 0
