_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.5
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
Model:
    value: |-
        DQN(
          (linear1): Linear(in_features=43, out_features=64, bias=True)
          (linear2): Linear(in_features=64, out_features=32, bias=True)
          (output): Linear(in_features=32, out_features=1, bias=True)
        )
batch_size:
    value: 128
checkpoint:
    value: Data/checkpoint66.pth
decay:
    value: 0
device:
    value: cuda
epochs:
    value: 20000
epochs per hat update:
    value: 3
gamma:
    value: 0.95
learning_rate:
    value: 5e-05
name:
    value: Herb_Keeper DDQN 66
start_epoch:
    value: 0
