_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 5
                - 14
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.5
            "5": 0.19.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
Model:
    value: |-
        DQN(
          (linear1): Linear(in_features=63, out_features=128, bias=True)
          (linear2): Linear(in_features=128, out_features=64, bias=True)
          (output): Linear(in_features=64, out_features=32, bias=True)
        )
Schedule:
    value: 'Counter({5000000: 1, 10000000: 1, 15000000: 1, 20000000: 1, 25000000: 1, 30000000: 1}) gamma=0.5'
batch_size:
    value: 128
checkpoint:
    value: Data/checkpoint7.pth
decay:
    value: 0
device:
    value: cpu
epochs:
    value: 20000
epochs per hat update:
    value: 3
gamma:
    value: 0.99
learning_rate:
    value: 0.002
name:
    value: Herb_Keeper DDQN 7
start_epoch:
    value: 2001
