_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
C:
    value: 3
Model:
    value: |-
        DQN(
          (linear1): Linear(in_features=123, out_features=128, bias=True)
          (linear2): Linear(in_features=128, out_features=64, bias=True)
          (output): Linear(in_features=64, out_features=40, bias=True)
        )
Schedule:
    value: 'Counter({5000000: 1, 10000000: 1, 15000000: 1, 20000000: 1, 25000000: 1, 30000000: 1}) gamma=0.5'
batch_size:
    value: 128
checkpoint:
    value: Data/checkpoint400.pth
decay:
    value: 0
device:
    value: cpu
epochs:
    value: 200000
gamma:
    value: 0.99
learning_rate:
    value: 0.005
name:
    value: Herb_Keeper DDQN 400
start_epoch:
    value: 0
tau:
    value: 0.001
